dist: xenial  # required for Python >= 3.7
language: python
install:
    - pip install codecov
    - pip install -r dev-requirements.txt
script:
    - make test
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8-dev'
  - 'nightly'
after_success:
    - codecov
