language: python
install:
    - pip install codecov
    - pip install -r dev-requirements.txt
script:
    - make test
matrix:
    include:
        - python: '3.5'
        - python: '3.6'
        - python: '3.7'
after_success:
    - codecov
